name: Bug Report
description: File a bug report here
title: "[Bug]"
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!!!

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
      description: Tell us what bug you encountered and what should have happened
    validations:
      required: true

  - type: textarea
    id: tests
    attributes:
      label: Test cases
      description: |
        Please paste the tests code that the bug fails.  
        Wrap it in triple backticks (```) for formatting.
      placeholder: |
        ```python
        def test_case():
            return 1/0
        ```
    validations:
      required: true

  - type: textarea
    id: correct-output
    attributes:
      label: Correct output
      description: Please paste in the correct output for the test code above.
    validations:
      required: true

  - type: textarea
    id: erroneous-code
    attributes:
      label: Code with error
      description: |
        Please paste the code that causes the bug.  
        Wrap it in triple backticks (```) for formatting.
      placeholder: |
        ```python
        def func():
            return 1/0
        ```
    validations:
      required: true

  - type: textarea
    id: wrong-output
    attributes:
      label: Wrong output
      description: If applicable, please paste in the wrong output generated.
    validations:
      required: false

  - type: checkboxes
    id: ai-fix
    attributes:
      label: Use AI-Powered fix
      description: Check if you want to try an AI-powered fix.
      options:
        - label: Use AI powered fix